CREATE TABLE `batches` (
	`_id` text PRIMARY KEY NOT NULL,
	`assessor` text NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`status` text NOT NULL,
	`noOfCandidates` integer NOT NULL,
	`durationInMin` integer NOT NULL,
	`no` text NOT NULL,
	`startDate` text NOT NULL,
	`endDate` text NOT NULL,
	`theoryQuestionBank` text NOT NULL,
	`practicalQuestionBank` text NOT NULL,
	`vivaQuestionBank` text NOT NULL,
	`isAssessorReached` integer NOT NULL,
	`isCandidateVideoRequired` integer NOT NULL,
	`isCandidatePhotosRequired` integer NOT NULL,
	`isCandidateLocationRequired` integer NOT NULL,
	`isCandidateAdharRequired` integer NOT NULL,
	`isCandidateSelfieRequired` integer NOT NULL,
	`isPracticalVisibleToCandidate` integer NOT NULL,
	`isSuspiciousActivityDetectionRequired` integer NOT NULL,
	`isAssessorEvidenceRequired` integer NOT NULL,
	`assessorReachedAt` text,
	`assessorCoordinates` text,
	`assessorGroupPhoto` text
);
--> statement-breakpoint
CREATE TABLE `candidates` (
	`_id` text PRIMARY KEY NOT NULL,
	`name` text,
	`email` text,
	`phone` text,
	`address` text,
	`batchId` text NOT NULL,
	`fatherName` text,
	`enrollmentNo` text NOT NULL,
	`isActive` integer NOT NULL,
	`password` text NOT NULL,
	`gender` text,
	`adharNo` text,
	`isTheoryStarted` integer NOT NULL,
	`isEvidanceUploaded` integer NOT NULL,
	`isPresentInTheory` integer NOT NULL,
	`isPresentInPractical` integer NOT NULL,
	`isPresentInViva` integer NOT NULL,
	`isTheorySubmitted` integer NOT NULL,
	`theoryExamStatus` text NOT NULL,
	`practicalExamStatus` text NOT NULL,
	`vivaExamStatus` text NOT NULL,
	`multipleFaceDetectionCount` integer NOT NULL,
	`faceHiddenCount` integer NOT NULL,
	`tabSwitchCount` integer NOT NULL,
	`exitFullScreenCount` integer NOT NULL,
	`theoryStartedAt` text,
	`theorySubmittedAt` text,
	`candidateSelfieCoordinates` text,
	`candidateSelfieTakenAt` text,
	`candidateSelfie` text,
	`adharPicture` text,
	`resetedAt` text,
	`practicalStartedAt` text,
	`practicalSubmittedAt` text
);
--> statement-breakpoint
CREATE TABLE `exam_response` (
	`candidateId` text NOT NULL,
	`batchId` text NOT NULL,
	`questionId` text NOT NULL,
	`answerId` text NOT NULL,
	`startedAt` text NOT NULL,
	`endedAt` text NOT NULL,
	`type` text DEFAULT 'THEORY' NOT NULL,
	`marksObtained` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(`questionId`, `candidateId`)
);
