-- CreateTable
CREATE TABLE "candidates" (
    "_id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "batchId" TEXT NOT NULL,
    "fatherName" TEXT,
    "enrollmentNo" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL,
    "password" TEXT NOT NULL,
    "gender" TEXT,
    "adharNo" TEXT,
    "isTheoryStarted" BOOLEAN NOT NULL,
    "isEvidanceUploaded" BOOLEAN NOT NULL,
    "isPresentInTheory" BOOLEAN NOT NULL,
    "isPresentInPractical" BOOLEAN NOT NULL,
    "isPresentInViva" BOOLEAN NOT NULL,
    "isTheorySubmitted" BOOLEAN NOT NULL,
    "theoryExamStatus" TEXT NOT NULL,
    "practicalExamStatus" TEXT NOT NULL,
    "vivaExamStatus" TEXT NOT NULL,
    "multipleFaceDetectionCount" INTEGER NOT NULL,
    "faceHiddenCount" INTEGER NOT NULL,
    "tabSwitchCount" INTEGER NOT NULL,
    "exitFullScreenCount" INTEGER NOT NULL,
    CONSTRAINT "candidates_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "batches" ("_id") ON DELETE RESTRICT ON UPDATE CASCADE
);
